import { envelope, type Seed } from '../_shared';

const photoResponse = (prompt: string) => ({ mode: 'photo' as const, prompt, maxAssets: 1 });

export const handwritingExpansionSeeds: Seed[] = [
  {
    ...envelope({
      id: '21000000-0000-4000-8000-000000000001',
      slug: 'luyen-viet-tu-chi-mau-sac',
      title: 'Luyện viết từ chỉ màu sắc',
      instructions: 'Con tô theo nét rồi tự viết mỗi từ hai lần nhé.',
      band: 'early',
      difficulty: 2,
      estimatedMinutes: 10,
      interestTags: ['drawing'],
      layout: 'worksheet',
    }),
    type: 'handwriting',
    response: photoResponse('Chụp trang con vừa viết'),
    payload: {
      script: 'print',
      unit: 'words',
      items: ['đỏ', 'cam', 'vàng', 'xanh', 'tím'],
      repetitions: 2,
      ruling: 'o_ly_grid',
      tracingGuides: true,
      focusDiacritics: ['đỏ', 'vàng', 'tím'],
    },
  },
  {
    ...envelope({
      id: '21000000-0000-4000-8000-000000000002',
      slug: 'luyen-viet-cau-ve-thoi-tiet',
      title: 'Luyện viết câu về thời tiết',
      instructions: 'Con viết lại từng câu hai lần và nhớ đặt dấu chấm.',
      band: 'lower_primary',
      difficulty: 2,
      estimatedMinutes: 12,
      interestTags: ['weather'],
      layout: 'worksheet',
    }),
    type: 'handwriting',
    response: photoResponse('Chụp trang con vừa viết'),
    payload: {
      script: 'print',
      unit: 'sentence',
      items: ['Hôm nay trời có nắng.', 'Mây trắng trôi trên cao.', 'Gió thổi làm lá rung.'],
      repetitions: 2,
      ruling: 'five_line',
      tracingGuides: false,
      focusDiacritics: ['ờ', 'ắ', 'ắ', 'ổ'],
    },
  },
  {
    ...envelope({
      id: '21000000-0000-4000-8000-000000000003',
      slug: 'viet-cau-ghi-chu-thien-nhien',
      title: 'Viết câu ghi chú về thiên nhiên',
      instructions: 'Con chép từng câu thật rõ rồi gạch dưới từ quan trọng.',
      band: 'upper_primary',
      difficulty: 2,
      estimatedMinutes: 12,
      interestTags: ['nature'],
      layout: 'worksheet',
    }),
    type: 'handwriting',
    response: photoResponse('Chụp trang ghi chú của con'),
    payload: {
      script: 'print',
      unit: 'sentence',
      items: ['Lá cây cần ánh sáng.', 'Rễ cây hút nước từ đất.', 'Hoa có nhiều màu sắc.'],
      repetitions: 1,
      ruling: 'single_line',
      tracingGuides: false,
      focusDiacritics: ['á', 'ướ', 'ề'],
    },
  },
  {
    ...envelope({
      id: '21000000-0000-4000-8000-000000000004',
      slug: 'luyen-chu-noi-tu-khoa-hoc',
      title: 'Luyện chữ nối với từ khoa học',
      instructions: 'Con viết chậm từng từ và giữ khoảng cách giữa các chữ.',
      band: 'upper_primary',
      difficulty: 3,
      estimatedMinutes: 12,
      interestTags: ['science'],
      layout: 'worksheet',
    }),
    type: 'handwriting',
    response: photoResponse('Chụp trang con vừa viết'),
    payload: {
      script: 'cursive',
      unit: 'words',
      items: ['năng lượng', 'không khí', 'nhiệt độ', 'ánh sáng', 'chuyển động'],
      repetitions: 2,
      ruling: 'four_line',
      tracingGuides: false,
      focusDiacritics: ['ượ', 'í', 'ệ', 'á'],
    },
  },
  {
    ...envelope({
      id: '21000000-0000-4000-8000-000000000005',
      slug: 'trinh-bay-cau-ve-vu-tru',
      title: 'Trình bày câu ngắn về vũ trụ',
      instructions: 'Con chép các câu và căn lề để trang viết dễ đọc.',
      band: 'upper_primary',
      difficulty: 4,
      estimatedMinutes: 15,
      interestTags: ['space'],
      layout: 'worksheet',
    }),
    type: 'handwriting',
    response: photoResponse('Chụp trang trình bày của con'),
    payload: {
      script: 'print',
      unit: 'sentence',
      items: [
        'Trái Đất quay quanh Mặt Trời.',
        'Mặt Trăng quay quanh Trái Đất.',
        'Bầu trời đêm có nhiều ngôi sao.',
      ],
      repetitions: 1,
      ruling: 'single_line',
      tracingGuides: false,
      focusDiacritics: ['á', 'ấ', 'ờ', 'ề'],
    },
  },
  {
    ...envelope({
      id: '21000000-0000-4000-8000-000000000006',
      slug: 'ghi-chu-ba-y-chinh',
      title: 'Ghi chú ba ý chính',
      instructions: 'Con chép ba ý và trình bày mỗi ý trên một dòng.',
      band: 'preteen',
      difficulty: 3,
      estimatedMinutes: 12,
      interestTags: ['science'],
      layout: 'worksheet',
    }),
    type: 'handwriting',
    response: photoResponse('Chụp trang ghi chú của con'),
    payload: {
      script: 'print',
      unit: 'sentence',
      items: [
        'Nước bay hơi khi được làm ấm.',
        'Hơi nước gặp lạnh tạo thành giọt.',
        'Nước lại trở về mặt đất.',
      ],
      repetitions: 1,
      ruling: 'single_line',
      tracingGuides: false,
      focusDiacritics: ['nước', 'lạnh', 'trở'],
    },
  },
  {
    ...envelope({
      id: '21000000-0000-4000-8000-000000000007',
      slug: 'trinh-bay-tieu-de-va-y-ngan',
      title: 'Trình bày tiêu đề và ý ngắn',
      instructions: 'Con chép tiêu đề rồi viết các ý ngắn thật thẳng hàng.',
      band: 'preteen',
      difficulty: 4,
      estimatedMinutes: 15,
      interestTags: ['travel'],
      layout: 'worksheet',
    }),
    type: 'handwriting',
    response: photoResponse('Chụp trang trình bày của con'),
    payload: {
      script: 'print',
      unit: 'sentence',
      items: [
        'Chuẩn bị cho chuyến đi.',
        '- Mang nước uống.',
        '- Kiểm tra thời tiết.',
        '- Giữ đồ dùng gọn gàng.',
      ],
      repetitions: 1,
      ruling: 'single_line',
      tracingGuides: false,
      focusDiacritics: ['ẩ', 'ướ', 'ế', 'ọ'],
    },
  },
  {
    ...envelope({
      id: '21000000-0000-4000-8000-000000000008',
      slug: 'viet-cac-dong-nhac-viec-hoc',
      title: 'Viết các dòng nhắc việc học',
      instructions: 'Con chép các dòng và tự chọn cách đánh dấu việc quan trọng.',
      band: 'preteen',
      difficulty: 5,
      estimatedMinutes: 15,
      interestTags: ['science'],
      layout: 'worksheet',
    }),
    type: 'handwriting',
    response: photoResponse('Chụp trang con vừa trình bày'),
    payload: {
      script: 'cursive',
      unit: 'sentence',
      items: [
        'Đọc lại phần đã học.',
        'Ghi ba từ khóa chính.',
        'Tự đặt một câu hỏi.',
        'Kiểm tra lại câu trả lời.',
      ],
      repetitions: 1,
      ruling: 'single_line',
      tracingGuides: false,
      focusDiacritics: ['Đọc', 'đã', 'khóa', 'Kiểm'],
    },
  },
];
