import { envelope, type Seed } from '../_shared';

const photoResponse = (prompt: string) => ({ mode: 'photo' as const, prompt, maxAssets: 1 });

export const handwritingSeeds: Seed[] = [
  {
    ...envelope({
      id: '20000000-0000-4000-8000-000000000001',
      slug: 'luyen-viet-nguyen-am-co-dau',
      title: 'Luyện viết nguyên âm có dấu',
      instructions: 'Con tô theo nét mờ. Rồi con tự viết lại mỗi chữ ba lần nhé.',
      parentNote: 'Bố mẹ nhắc con ngồi thẳng lưng và cầm bút thoải mái, không cần vội.',
      band: 'early',
      difficulty: 1,
      estimatedMinutes: 10,
      layout: 'worksheet',
    }),
    type: 'handwriting',
    response: photoResponse('Chụp trang con vừa viết'),
    payload: {
      script: 'print',
      unit: 'letters',
      items: ['a', 'ă', 'â', 'e', 'ê', 'o', 'ô', 'ơ'],
      repetitions: 3,
      ruling: 'o_ly_grid',
      tracingGuides: true,
      focusDiacritics: ['ă', 'â', 'ê', 'ô', 'ơ'],
    },
  },
  {
    ...envelope({
      id: '20000000-0000-4000-8000-000000000002',
      slug: 'luyen-viet-tu-ve-gia-dinh',
      title: 'Luyện viết từ về gia đình',
      instructions: 'Con viết lại mỗi từ ba lần. Con nhớ viết dấu cho đúng nhé.',
      band: 'early',
      difficulty: 2,
      estimatedMinutes: 12,
      interestTags: ['family'],
      layout: 'worksheet',
    }),
    type: 'handwriting',
    response: photoResponse('Chụp trang con vừa viết'),
    payload: {
      script: 'print',
      unit: 'words',
      items: ['bà', 'ông', 'mẹ', 'bố', 'chị', 'anh', 'em'],
      repetitions: 3,
      ruling: 'o_ly_grid',
      tracingGuides: true,
      focusDiacritics: ['à', 'ô', 'ẹ', 'ố'],
    },
  },
  {
    ...envelope({
      id: '20000000-0000-4000-8000-000000000003',
      slug: 'luyen-viet-cau-ngan-ve-con-vat',
      title: 'Luyện viết câu ngắn về con vật',
      instructions: 'Con hãy viết lại câu dưới đây hai lần, viết hoa chữ đầu câu nhé.',
      band: 'lower_primary',
      difficulty: 2,
      estimatedMinutes: 12,
      interestTags: ['animals'],
      layout: 'worksheet',
    }),
    type: 'handwriting',
    response: photoResponse('Chụp trang con vừa viết'),
    payload: {
      script: 'print',
      unit: 'sentence',
      items: ['Chú mèo con nằm sưởi nắng.', 'Đàn kiến nhỏ đang tha mồi.'],
      repetitions: 2,
      ruling: 'five_line',
      tracingGuides: false,
      focusDiacritics: ['ú', 'è', 'ằ', 'ưở'],
    },
  },
  {
    ...envelope({
      id: '20000000-0000-4000-8000-000000000004',
      slug: 'luyen-viet-tu-kho-dau-nga',
      title: 'Luyện viết từ khó có dấu ngã',
      instructions: 'Dấu ngã hơi khó viết. Con viết mỗi từ ba lần thật chậm nhé.',
      parentNote: 'Dấu ngã và dấu hỏi hay bị nhầm. Bố mẹ đọc to từng từ cho con nghe nhé.',
      band: 'lower_primary',
      difficulty: 3,
      estimatedMinutes: 12,
      layout: 'worksheet',
    }),
    type: 'handwriting',
    response: photoResponse('Chụp trang con vừa viết'),
    payload: {
      script: 'print',
      unit: 'words',
      items: ['ngã', 'vẽ', 'cũ', 'mãi', 'nhãn', 'kỹ', 'sẽ'],
      repetitions: 3,
      ruling: 'five_line',
      tracingGuides: false,
      focusDiacritics: ['ã', 'ẽ', 'ũ', 'ỹ'],
    },
  },
];
